// Generated by scripts/build-atlases.ts. The atlas images, for React Native
// only (node tests import frames.generated.ts instead).

import type { AtlasName } from './frames.generated';

export const ATLAS_SOURCES: Record<AtlasName, number> = {
  "shared": require('./atlases/shared.png'),
  "forest": require('./atlases/forest.png'),
  "swamp": require('./atlases/swamp.png'),
  "desert": require('./atlases/desert.png'),
  "frost": require('./atlases/frost.png'),
  "iron": require('./atlases/iron.png'),
  "volcano": require('./atlases/volcano.png'),
  "astral": require('./atlases/astral.png'),
};
