// Generated by scripts/credits.ts. Do not edit. What the Scribe's Credits screen lists.

export interface PackCredit { title: string; author: string; license: string; url: string; uses: string }

export const PACK_CREDITS: PackCredit[] = [
  {
    "title": "Impact Sounds (1.0)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/impact-sounds",
    "uses": "3 sounds"
  },
  {
    "title": "Interface Sounds (1.0)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/interface-sounds",
    "uses": "1 sound"
  },
  {
    "title": "Music Jingles (1.0)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/music-jingles",
    "uses": "4 sounds"
  },
  {
    "title": "RPG Audio (1.0)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/rpg-audio",
    "uses": "1 sound"
  },
  {
    "title": "Tiny Dungeon (1.0)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/tiny-dungeon",
    "uses": "3 sprites"
  },
  {
    "title": "Tiny Town (1.1)",
    "author": "Kenney (www.kenney.nl)",
    "license": "CC0",
    "url": "https://kenney.nl/assets/tiny-town",
    "uses": "35 sprites"
  }
];

/** Sprites still drawn from Adet's original stand-in art. */
export const STAND_IN_SPRITES = 330;
