// Generated by scripts/build-audio.ts. The sound files, for React Native
// only (node tests import sounds.generated.ts instead).

export const SOUND_SOURCES: Record<string, number> = {
  "boss_defeat": require('../../../assets/game/audio/boss_defeat.m4a'),
  "chest_open": require('../../../assets/game/audio/chest_open.m4a'),
  "crit": require('../../../assets/game/audio/crit.m4a'),
  "gate_open": require('../../../assets/game/audio/gate_open.m4a'),
  "hit": require('../../../assets/game/audio/hit.m4a'),
  "level_up": require('../../../assets/game/audio/level_up.m4a'),
  "purchase": require('../../../assets/game/audio/purchase.m4a'),
  "rank_up": require('../../../assets/game/audio/rank_up.m4a'),
  "ui_tap": require('../../../assets/game/audio/ui_tap.m4a'),
};
