// Generated by scripts/build-audio.ts (npm run game:audio). Do not edit.
// SFX id → the built file, where it came from, its length and size.

export const SOUND_FILES: Record<string, { pack: string; file: string; seconds: number; bytes: number }> = {
  "boss_defeat": {"pack":"kenney-music-jingles","file":"boss_defeat.m4a","seconds":1.26,"bytes":11341},
  "chest_open": {"pack":"kenney-impact-sounds","file":"chest_open.m4a","seconds":0.26,"bytes":3231},
  "crit": {"pack":"kenney-impact-sounds","file":"crit.m4a","seconds":0.11,"bytes":2070},
  "gate_open": {"pack":"kenney-music-jingles","file":"gate_open.m4a","seconds":1.05,"bytes":9665},
  "hit": {"pack":"kenney-impact-sounds","file":"hit.m4a","seconds":0.12,"bytes":2057},
  "level_up": {"pack":"kenney-music-jingles","file":"level_up.m4a","seconds":0.91,"bytes":8519},
  "purchase": {"pack":"kenney-rpg-audio","file":"purchase.m4a","seconds":0.21,"bytes":2917},
  "rank_up": {"pack":"kenney-music-jingles","file":"rank_up.m4a","seconds":1.39,"bytes":12454},
  "ui_tap": {"pack":"kenney-interface-sounds","file":"ui_tap.m4a","seconds":0.04,"bytes":1486},
};
