// Writes docs/quest/art/INVENTORY.md: every logical sprite id, grouped by
// category, with where its art comes from (pack, recolor, composed, or
// needs-art with the reason). Run after `npm run game:assets`.
//
//   npm run game:report

import fs from 'node:fs';
import path from 'node:path';

import { REQUIRED_IDS } from '../src/game/assets/manifest';
import { SPRITE_SOURCES } from '../src/game/assets/sources.generated';
import type { MappedSprite } from './art-sources';
import { loadRegistry } from './packs';

const ROOT = path.resolve(__dirname, '..');
const NEEDS_ART: Record<string, string> = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/game/needs-art.json'), 'utf8'));

const CATEGORIES: [string, RegExp][] = [
  ['Mobs', /^mob\./],
  ['Bosses and trophies', /^(boss|trophy)\./],
  ['NPCs', /^npc\./],
  ['Villagers', /^villager\./],
  ['Critters', /^critter\./],
  ['Avatar (body, tiers, cosmetics)', /^avatar\./],
  ['Companions', /^pet\./],
  ['Ground and path tiles', /^tile\.[a-z]+\.(ground|path)\./],
  ['Island edges and liquids', /^tile\./],
  ['Decor', /^decor\./],
  ['Biome props (gates, graves, flags)', /^prop\.[a-z]+\.(gate|grave|flag)/],
  ['Camp props (campfires, chests, board)', /^prop\./],
  ['Parallax', /^parallax\./],
  ['FX', /^fx\./],
  ['UI icons (and shop item icons)', /^icon\./],
];

const base = (id: string) => id.replace(/@(flip|flash)$/, '');
const sourceOf = (id: string) => SPRITE_SOURCES[base(id)] ?? SPRITE_SOURCES[id] ?? 'missing';

function main() {
  const ids = [...new Set(REQUIRED_IDS.map(base))].sort();
  const groups = new Map<string, string[]>(CATEGORIES.map(([name]) => [name, []]));
  for (const id of ids) groups.get(CATEGORIES.find(([, re]) => re.test(id))?.[0] ?? 'Other')?.push(id) ?? groups.set('Other', [id]);
  const kind = (s: string) => s.split(':')[0];
  const total = new Map<string, number>();
  for (const id of ids) total.set(kind(sourceOf(id)), (total.get(kind(sourceOf(id))) ?? 0) + 1);
  const lines: string[] = [
    '# Quest art inventory',
    '',
    'Generated by `npm run game:report` (scripts/asset-report.ts) from',
    '`src/game/assets/sources.generated.ts`, which `npm run game:assets` writes. Mirrored',
    '(`@flip`) and hit-flash (`@flash`) variants are derived from their base sprite and not',
    'listed separately.',
    '',
    '| Source | Ids |',
    '|---|---|',
    ...['pack', 'recolor', 'composed', 'needs-art', 'generated-placeholder', 'missing'].map((k) => `| ${k} | ${total.get(k) ?? 0} |`),
    '',
    '`needs-art` ids still ship Adet\'s original stand-in art (drawn in code, so the game is',
    'complete) until a licensed pack provides them; each is listed in',
    '`assets/game/needs-art.json` with what is needed and which packs were searched.',
    '`generated-placeholder` (a stand-in with no allowlist entry) must stay at 0: the build',
    'refuses it.',
    '',
  ];
  for (const [name, list] of groups) {
    if (!list.length) continue;
    const counts = new Map<string, number>();
    for (const id of list) counts.set(kind(sourceOf(id)), (counts.get(kind(sourceOf(id))) ?? 0) + 1);
    lines.push(`## ${name} (${list.length})`, '', [...counts].map(([k, v]) => `${k} ${v}`).join(' · '), '');
    const reasons = new Map<string, string[]>();
    const real: string[] = [];
    for (const id of list) {
      const s = sourceOf(id);
      if (s === 'needs-art') {
        const why = NEEDS_ART[id] ?? NEEDS_ART[`${id}@flip`] ?? '(no reason recorded)';
        reasons.set(why, [...(reasons.get(why) ?? []), id]);
      } else real.push(`| \`${id}\` | ${s} |`);
    }
    if (real.length) lines.push('| Id | Source |', '|---|---|', ...real, '');
    for (const [why, group] of reasons) lines.push(`**needs-art (${group.length}):** ${why}`, '', group.map((i) => `\`${i}\``).join(', '), '');
  }
  fs.mkdirSync(path.join(ROOT, 'docs/quest/art'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'docs/quest/art/INVENTORY.md'), lines.join('\n') + '\n');
  console.log(`docs/quest/art/INVENTORY.md: ${ids.length} ids (${[...total].map(([k, v]) => `${k} ${v}`).join(', ')})`);
  writeMapping();
}

/** docs/quest/art/MAPPING.md from the registry: every mapped id, its source, transform and why it fits. */
function writeMapping() {
  const packs = loadRegistry();
  const rows: string[] = [];
  for (const p of packs)
    for (const [id, raw] of Object.entries(p.sprites ?? {}) as [string, MappedSprite][]) {
      const frames = raw.tiles ? `tile${raw.tiles.length > 1 ? 's' : ''} ${raw.tiles.join(', ')}` : `${raw.rects?.length ?? 0} rect(s)`;
      const transform = [
        raw.ramp ? `recolour: tones onto ${raw.palette} ${raw.ramp.name}[${raw.ramp.from}–${raw.ramp.to}]` : raw.palette ? `recolour: nearest ${raw.palette} palette colour` : null,
        raw.mask ? `mask: ellipse ${raw.mask.ellipse.join(', ')}` : null,
        raw.offsets ? `frames: offsets ${raw.offsets.map((o) => o.join(',')).join(' / ')}` : null,
      ].filter(Boolean).join('; ') || 'none';
      rows.push(`| \`${id}\` | ${p.title}: \`${raw.file ?? raw.sheet}\` ${frames} | ${transform} | ${raw.why ?? ''} |`);
    }
  for (const p of packs)
    for (const [id, snd] of Object.entries(p.sounds ?? {})) rows.push(`| \`sfx:${id}\` | ${p.title}: \`${snd.file}\` | trim, mono, even loudness${snd.gain ? `, ${snd.gain} dB` : ''}, AAC | ${snd.why ?? ''} |`);
  const md = [
    '# Art and audio mapping',
    '',
    'Generated by `npm run game:report` from the pack registry (`assets/game/packs/*.json`),',
    'which is the only place mappings live. Every logical id not listed here keeps Adet\'s',
    'stand-in art; why, per category, is in `INVENTORY.md`.',
    '',
    'Fallback ladder for each id: pack sprite → recoloured pack sprite → composed from pack',
    'parts → `needs-art`. A mismatched sprite is never used just to fill a slot.',
    '',
    '| Id | Source | Transform | Why it fits |',
    '|---|---|---|---|',
    ...rows,
    '',
    '## What the stand-ins are waiting for',
    '',
    'Bosses should read as what they represent (from the spec):',
    '',
    '| Boss | Should read as | Look for in a pack |',
    '|---|---|---|',
    '| Fog Wisp | drifting spirit of mist | ghost, wisp, spirit (recolour pale green-white) |',
    '| Doomscroll Hydra | multi-headed serpent | serpent, snake or dragon heads; compose several heads on a body |',
    '| Mirage Djinn | genie rising from sand | genie, spirit, mage, ghost with the sand palette |',
    '| Frozen Titan | massive ice golem | golem, giant, yeti, stone guardian (recolour to ice blues) |',
    '| King Tomorrow | crowned king in stone, red and gold | king, knight, ruler; add a crown if needed |',
    '| Burnout Drake | fire dragon | dragon or drake (charcoal and magma orange) |',
    '| Hollow Echo | void shade | dark spirit, shadow, ghost (indigo and cyan) |',
    '',
    'Mobs follow the spec\'s names (Moss Slime, Thorn Sprite, Mushroom Imp…); NPCs are an owl',
    '(Aqyl), a fox (Saudager) and a tortoise (Hatshy), where a nearest animal plus a small',
    'accessory composed from pack parts is fine. See `docs/quest/OWNER_ACTIONS.md` for the pack',
    'most likely to cover them.',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(ROOT, 'docs/quest/art/MAPPING.md'), md);
  console.log(`docs/quest/art/MAPPING.md: ${rows.length} mappings`);
}

main();
