// Builds Quest's sounds from the licensed packs: each SFX id mapped in a
// pack's registry entry (assets/game/packs/*.json) is trimmed of silence,
// made mono, brought to one quiet loudness, and encoded as AAC (.m4a, which
// iOS plays; it can't play the packs' OGG). No audio is synthesised.
//
//   npm run game:fetch && npm run game:audio
//
// Outputs: assets/game/audio/<id>.m4a, src/game/assets/sounds.generated.ts
// (node-safe metadata), src/game/assets/soundSources.ts (RN requires), and
// the credits (scripts/credits.ts).

import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

import { writeCredits } from './credits';
import { loadRegistry, requirePack, ROOT } from './packs';

const OUT = path.join(ROOT, 'assets/game/audio');
const GEN = path.join(ROOT, 'src/game/assets');
/** Target mean loudness for every SFX, in dBFS: even across packs and a little under the app's own sounds (about -17). */
const TARGET_MEAN_DB = -22;
/** Never let a peak above this through. */
const PEAK_DB = -4;
/** A single sound effect must stay small and short. */
const MAX_SFX_BYTES = 60 * 1024;
const MAX_SFX_SECONDS = 2.5;

const ffmpeg = (args: string[]) => execFileSync('ffmpeg', ['-hide_banner', '-v', 'error', ...args], { stdio: ['ignore', 'pipe', 'pipe'] });

/** ffmpeg's filter reports (volumedetect) go to stderr. */
function stderrOf(args: string[]): string {
  return String(spawnSync('ffmpeg', args, { encoding: 'utf8' }).stderr ?? '');
}

function duration(file: string): number {
  return Number(execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file]).toString().trim());
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const f of fs.readdirSync(OUT)) if (f.endsWith('.m4a')) fs.unlinkSync(path.join(OUT, f));
  const built: { id: string; pack: string; file: string; seconds: number; bytes: number }[] = [];
  const tmp = path.join(OUT, '.trimmed.wav');
  for (const pack of loadRegistry()) {
    for (const [id, s] of Object.entries(pack.sounds ?? {})) {
      const src = path.join(requirePack(pack), s.file);
      if (!fs.existsSync(src)) throw new Error(`${pack.name}: ${s.file} not found`);
      // 1. Trim leading and trailing silence, mono, 44.1 kHz.
      ffmpeg(['-y', '-i', src, '-af', 'silenceremove=start_periods=1:start_threshold=-50dB,areverse,silenceremove=start_periods=1:start_threshold=-50dB,areverse', '-ac', '1', '-ar', '44100', tmp]);
      // 2. One quiet loudness: gain toward the target mean, capped by the peak limit.
      const err = stderrOf(['-hide_banner', '-i', tmp, '-af', 'volumedetect', '-f', 'null', '-']);
      const mean = Number(/mean_volume: (-?[\d.]+) dB/.exec(err)?.[1]);
      const max = Number(/max_volume: (-?[\d.]+) dB/.exec(err)?.[1]);
      if (!Number.isFinite(mean) || !Number.isFinite(max)) throw new Error(`could not measure ${src}`);
      const gain = Math.min(TARGET_MEAN_DB - mean, PEAK_DB - max) + (s.gain ?? 0);
      const out = path.join(OUT, `${id}.m4a`);
      // 3. AAC in .m4a, mono, bit-exact so rebuilding gives the same bytes.
      ffmpeg(['-y', '-i', tmp, '-af', `volume=${gain.toFixed(2)}dB`, '-c:a', 'aac', '-b:a', '64k', '-map_metadata', '-1', '-fflags', '+bitexact', '-flags:a', '+bitexact', out]);
      const seconds = duration(out);
      const bytes = fs.statSync(out).size;
      if (bytes > MAX_SFX_BYTES || seconds > MAX_SFX_SECONDS) throw new Error(`${id}: ${bytes} B, ${seconds.toFixed(2)} s is over the SFX limit`);
      built.push({ id, pack: pack.name, file: `${id}.m4a`, seconds: Math.round(seconds * 100) / 100, bytes });
      console.log(`  ${id.padEnd(12)} ${pack.name}/${s.file}  ${seconds.toFixed(2)} s  ${(bytes / 1024).toFixed(1)} KB  gain ${gain.toFixed(1)} dB`);
    }
  }
  if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
  built.sort((a, b) => (a.id < b.id ? -1 : 1));
  fs.writeFileSync(
    path.join(GEN, 'sounds.generated.ts'),
    `// Generated by scripts/build-audio.ts (npm run game:audio). Do not edit.\n` +
      `// SFX id → the built file, where it came from, its length and size.\n\n` +
      `export const SOUND_FILES: Record<string, { pack: string; file: string; seconds: number; bytes: number }> = {\n` +
      built.map((b) => `  ${JSON.stringify(b.id)}: ${JSON.stringify({ pack: b.pack, file: b.file, seconds: b.seconds, bytes: b.bytes })},`).join('\n') +
      `\n};\n`
  );
  fs.writeFileSync(
    path.join(GEN, 'soundSources.ts'),
    `// Generated by scripts/build-audio.ts. The sound files, for React Native\n// only (node tests import sounds.generated.ts instead).\n\n` +
      `export const SOUND_SOURCES: Record<string, number> = {\n` +
      built.map((b) => `  ${JSON.stringify(b.id)}: require('../../../assets/game/audio/${b.file}'),`).join('\n') +
      `\n};\n`
  );
  writeCredits();
  console.log(`wrote ${built.length} sounds`);
}

Promise.resolve().then(main).catch((e) => {
  // A missing pack or a refused stand-in is a message, not a crash.
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
