// One source for credits: assets/game/CREDITS.md (for people) and
// src/game/assets/credits.generated.ts (the Scribe's Credits screen), both
// from the pack registry. Called by game:assets and game:audio.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { LICENSES, loadRegistry, Pack, PERMISSIVE, ROOT } from './packs';

interface Evaluated {
  name: string;
  url: string;
  license: string;
  reason: string;
}

const readJson = <T,>(p: string, fallback: T): T => (fs.existsSync(p) ? (JSON.parse(fs.readFileSync(p, 'utf8')) as T) : fallback);

const uses = (p: Pack) => {
  const sprites = Object.keys(p.sprites ?? {}).length;
  const sounds = Object.keys(p.sounds ?? {}).length;
  const n = (k: number, one: string) => (k ? `${k} ${one}${k === 1 ? '' : 's'}` : null);
  return [n(sprites, 'sprite'), n(sounds, 'sound')].filter(Boolean).join(', ');
};

export function writeCredits() {
  const packs = loadRegistry();
  const used = packs.filter((p) => uses(p));
  const evaluated = readJson<Evaluated[]>(path.join(ROOT, 'assets/game/packs/evaluated.json'), []);
  const needsArt = readJson<Record<string, string>>(path.join(ROOT, 'assets/game/needs-art.json'), {});
  const needsAudio = readJson<Record<string, string>>(path.join(ROOT, 'assets/game/needs-audio.json'), {});
  const licenseSum = (p: Pack) => {
    const f = path.join(LICENSES, p.name, 'License.txt');
    return fs.existsSync(f) ? crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex').slice(0, 12) : 'missing';
  };
  const row = (p: Pack) =>
    `| ${p.title} | ${p.author} | [${p.license}](${p.licenseUrl}) | ${p.url} | ${p.downloaded ?? '—'} | \`${p.sha256 ? p.sha256.slice(0, 16) : '—'}…\` | ${uses(p) || '—'} | ${PERMISSIVE.test(p.license) ? `license copy \`${licenseSum(p)}\`` : '⚠️ not an allowed license'} |`;

  const md = `# Quest Mode art & audio credits

Generated by \`scripts/credits.ts\` (run by \`npm run game:assets\` and
\`npm run game:audio\`) from the pack registry in \`assets/game/packs/\`. Edit
the registry, not this file. Each pack's own license text is kept in
\`assets/game/licenses/<pack>/\`.

## Licensed packs in use

Policy: CC0, CC-BY (with attribution below and in the app), or an explicitly
permissive license only. No NonCommercial, ShareAlike/GPL, personal-use-only
or unlicensed assets.

| Pack | Author | License | Source | Downloaded | Zip sha256 | Used for | Notes |
|---|---|---|---|---|---|---|---|
${used.length ? used.map(row).join('\n') : '| _none_ | | | | | | | |'}

${packs.length > used.length ? `Registered but not used yet: ${packs.filter((p) => !uses(p)).map((p) => p.title).join(', ')}.\n` : ''}
## Evaluated, not used

| Pack | License | Source | Why not |
|---|---|---|---|
${evaluated.length ? evaluated.map((e) => `| ${e.name} | ${e.license} | ${e.url} | ${e.reason} |`).join('\n') : '| _none_ | | | |'}

## Original art (stand-ins)

Sprites no licensed pack provides yet keep Adet's original pixel art, drawn in
code by \`scripts/gen-placeholders.ts\` (palette-indexed grids), released with the
app under the same terms as its source. Each one is listed, with the kind of
art it needs, in \`assets/game/needs-art.json\` (${Object.keys(needsArt).length} ids) and
\`docs/quest/art/INVENTORY.md\`.

## Audio still missing

${Object.keys(needsAudio).length ? Object.entries(needsAudio).map(([id, why]) => `- \`${id}\`: ${why}`).join('\n') : 'None.'}

## Fonts

| Font | Author | License | Source |
|---|---|---|---|
| Pixelify Sans | Stefie Justprince | SIL Open Font License 1.1 | https://fonts.google.com/specimen/Pixelify+Sans |
| Silkscreen | Jason Kottke | SIL Open Font License 1.1 | https://fonts.google.com/specimen/Silkscreen |
`;
  fs.writeFileSync(path.join(ROOT, 'assets/game/CREDITS.md'), md);

  const data = used.map((p) => ({ title: p.title, author: p.author, license: p.license, url: p.url, uses: uses(p) }));
  fs.writeFileSync(
    path.join(ROOT, 'src/game/assets/credits.generated.ts'),
    `// Generated by scripts/credits.ts. Do not edit. What the Scribe's Credits screen lists.\n\n` +
      `export interface PackCredit { title: string; author: string; license: string; url: string; uses: string }\n\n` +
      `export const PACK_CREDITS: PackCredit[] = ${JSON.stringify(data, null, 2)};\n\n` +
      `/** Sprites still drawn from Adet's original stand-in art. */\n` +
      `export const STAND_IN_SPRITES = ${Object.keys(needsArt).length};\n`
  );
}

if (require.main === module) writeCredits();
